# local proxy
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=8094
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=8094

org.gradle.jvmargs=-Xmx2G
archives_base_name=drg_flares
mod_id=drg_flares
mod_name=DRG Flares
mod_authors=["LizardOfOz"]
mod_description=Adds Flares from Deep Rock Galactic
github=https://github.com/Lizard-Of-Oz/DRG_Flares

minecraft_version=1.21.1
base_mc_version=1.21
mod_version=1.2.8

fabric_loader_version=0.14.21
fabric_api_version=0.84.0+1.20.1
yarn_mappings=1.21.1+build.3
parchment_mappingsVersion=2024.11.17

forge_version=47.0.35
neoforge_version=21.1.97
lombok_version=1.18.36

cloth_config_version=15.0.140
modmenu_version=7.1.0

kotlin.stdlib.default.dependency = false