modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "${github}"
license = "custom"

[[mixins]]
config="drg_flares.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="${github}"

[[dependencies.drg_flares]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drg_flares]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"